name: Deploy VitePress Site to GitHub Pages

on:
  push:
    branches:
      - main # 或者您希望触发部署的分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取所有历史记录，以支持子模块等

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # 或者您希望使用的 Node.js 版本

      - name: Install Dependencies
        run: |          
          npm ci
          # 或者使用 pnpm: pnpm install --no-optional

      - name: Build VitePress Site
        run: npm run docs:build
        # 或者使用 pnpm: pnpm docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist # 您的构建输出目录
          user_name: luoyuanxiang # 可选
          user_email: 1141306760@qq.com # 可选
          publish_branch: gh-pages
